config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :groups
  resources :entities

  resources :users, only: [:show]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "splash#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user

  has_many :entity_groups, dependent: :delete_all
  has_many :groups, through: :entity_groups

  accepts_nested_attributes_for :entity_groups, allow_destroy: true

  validates :name, presence: true
  validates :name, length: { in: 3..30 }

  validates :amount, numericality: { only_integer: true }
  validates :amount, numericality: { greater_than_or_equal_to: 0 }
end

app/models/entity_group.rb
class EntityGroup < ApplicationRecord
  belongs_to :entity
  belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :entity_groups, dependent: :delete_all
  has_many :entities, through: :entity_groups

  validates :name, presence: true
  validates :name, length: { in: 3..30 }

  validates :icon, presence: true

  def price
    price = 0
    entities.each { |entity| price += entity.amount }
    price
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :entities, dependent: :delete_all
  has_many :groups, dependent: :delete_all

  validates :name, presence: true
  validates :name, length: { in: 3..30 }

  after_create :seed_groups

  def seed_groups
    return unless valid?

    groups.create(name: 'Food', icon: '013-display.png')
    groups.create(name: 'Household', icon: '017-home.png')
    groups.create(name: 'Medical', icon: '003-heartbeat.png')
    groups.create(name: 'Travel', icon: '012-transportation.png')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_params, if: :devise_controller?

  protected

  def update_allowed_params
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_entity, only: %i[show edit update destroy]
  before_action :redirect

  # GET /entities/1
  def show
    @groups = @entity.groups.all
    @header = { title: 'Transaction', url: edit_entity_path(@entity) }
  end

  # GET /entities/new
  def new
    @groups = current_user.groups.all
    @entity = Entity.new
    @entity.entity_groups.build
    @header = { title: 'New Transaction' }
  end

  # GET /entities/1/edit
  def edit
    @groups = current_user.groups.where.not(entity: @entity)
    @header = { title: 'Edit Transaction' }
  end

  # POST /entities or /entities.json
  def create
    @groups = current_user.groups.all
    @entity = Entity.new(entity_params)

    grp_ids = entity_params[:entity_groups_attributes]['0'][:group_id]
    startcount = 1

    @entity.entity_groups.each do |m|
      m.group_id = grp_ids[startcount]
      startcount += 1
    end

    respond_to do |format|
      if @entity.save
        grp_ids.drop(startcount).each do |_|
          @entity.entity_groups.build(group_id: grp_ids[startcount]).save
          startcount += 1
        end

        format.html { redirect_to groups_path, notice: 'Entity was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entities/1 or /entities/1.json
  def update
    respond_to do |format|
      if @entity.update(entity_params)
        format.html { redirect_to entity_url(@entity), notice: 'Entity was successfully updated.' }
        format.json { render :show, status: :ok, location: @entity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entities/1 or /entities/1.json
  def destroy
    @entity.destroy

    respond_to do |format|
      format.html { redirect_to entities_url, notice: 'Entity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def redirect
    redirect_to root_path unless current_user
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_entity
    @entity = Entity.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def entity_params
    params.require(:entity).permit(:name, :amount, entity_groups_attributes: [group_id: []]).merge(user: current_user)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :redirect
  before_action :set_group, only: %i[show edit update destroy]

  ICONS = [
    ['Entertainment', '001-theater.png'],
    ['Pets', '002-pet-house.png'],
    ['Health', '003-heartbeat.png'],
    ['Bills', '004-receipt.png'],
    ['Games', '005-controller.png'],
    ['Clothes', '006-hanger.png'],
    ['Toiletries', '007-toiletries.png'],
    ['Family', '008-family.png'],
    ['Miscellaneous', '009-miscellaneous.png'],
    ['Random', '010-rgb.png'],
    ['Gifts', '011-magic-box.png'],
    ['Travel', '012-transportation.png'],
    ['Groceries', '013-display.png'],
    ['Necessities', '014-must-have.png'],
    ['Personal', '015-profile.png'],
    ['Job', '016-job-offer.png'],
    ['Home', '017-home.png']
  ].freeze

  # GET /groups or /groups.json
  def index
    @groups = current_user.groups.includes([:entity_groups]).all
    @header = { title: 'Categories' }
  end

  # GET /groups/1 or /groups/1.json
  def show
    @transactions = @group.entities.all.order('created_at desc')
    @header = { title: 'Transactions', url: edit_group_path(@group) }
  end

  # GET /groups/new
  def new
    @group = Group.new
    @header = { title: 'New Category' }
  end

  # GET /groups/1/edit
  def edit
    @header = { title: 'Edit Category' }
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def redirect
    redirect_to root_path unless current_user
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon).merge(user: current_user)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def home
    redirect_to groups_path if current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entities/_entity.html.erb
<%= link_to entity, class: "grp box" do %>
  <div class="grp-text wrapper">
    <div class="grp-text txt-top">
      <h5><%= entity.name %></h5>
      <h4>$<%= entity.amount %></h4>
    </div>
    <hr>
    <div class="grp-text txt-bottom">
      <small>
        <%= entity.created_at.strftime('%a, %d %b %Y') %> at <%= entity.created_at.strftime('%-I:%M %p') %></small>
      </small>
    </div>
  </div>
<% end %>

app/views/entities/_form.html.erb
<%= form_with model: entity, html: { class: 'form' } do |f| %>
  <div class="fields">
  <% if entity.errors.any? %>
    <div class="alert">
      <h3><%= pluralize(entity.errors.count, "error") %> prohibited this entity from being saved:</h3>
      <ul>
        <% entity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.text_field :name, placeholder: t("ent_name"), autofocus: true, autocomplete: "name" %>
    </div>
    <div class="field">
      <%= f.text_field :amount, placeholder: t("ent_amount"), autocomplete: "amount" %>
    </div>
    <%= f.fields_for :entity_groups do |egf| %>
      <div class="field">
        <%= egf.label :group_id, "Please Select Groups for this Entity:" %>
        <%= egf.collection_select :group_id, @groups, :id, :name, {}, { multiple: true, size: @groups.size } %>
      </div>
    <% end %>
  </div>

  <div class="actions">
    <%= render "shared/notice" %>
    <%= f.submit t('save'), class: "active" %>
  </div>
<% end %>

app/views/entities/edit.html.erb
<%= form_with model: @entity, html: { class: 'form' } do |f| %>
  <div class="fields">
    <% if @entity.errors.any? %>
      <div class="alert">
        <h3><%= pluralize(@entity.errors.count, "error") %> prohibited this entity from being saved:</h3>
        <ul>
          <% @entity.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.text_field :name, placeholder: t("ent_name"), autofocus: true, autocomplete: "name" %>
    </div>
    <div class="field">
      <%= f.text_field :amount, placeholder: t("ent_amount"), autocomplete: "amount" %>
    </div>
  </div>

  <div class="actions">
    <%= render "shared/notice" %>
    <%= f.submit t('save'), class: "active" %>
  </div>
<% end %>

app/views/entities/new.html.erb
<%= render "form", entity: @entity %>

app/views/entities/show.html.erb
<div class="group entity box">
  <h2>
    <%# image_tag @group.icon || 'icon', style: 'height:64px;width:64px', class: 'grp-icon' %>
    <span><%= @entity.name %></span>
    <small>$<%= @entity.amount %></small>
  </h2>
  <hr>
  <%= render @groups %>
</div>

<div class="actions">
  <%= render "shared/notice" %>
  <%# button_to "Add Category", entities_path %>
</div>

app/views/groups/_form.html.erb
<%= form_with(model: group) do |f| %>
  <div class="fields">
  <% if group.errors.any? %>
    <div class="alert">
      <h5><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h5>
      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.text_field :name, placeholder: t("grp_name"), autofocus: true, autocomplete: "name" %>
    </div>
    <div class="field">
      <%= f.select :icon, options_for_select(GroupsController::ICONS), :prompt => t('select_icon') %>
    </div>
  </div>

  <div class="actions">
    <%= render "shared/notice" %>
    <%= f.submit t('save'), class: "active" %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<%= link_to group, class: "grp box" do %>
  <%= image_tag group.icon || 'icon', style: 'height:64px;width:64px', class: 'grp-icon' %>
  <div class="grp-text wrapper">
    <div class="grp-text txt-top">
      <h4><%= group.name %></h4>
      <h4>(<%= group.entity_groups.size %>)</h4>
    </div>
    <hr>
    <div class="grp-text txt-bottom">
      <small><%= group.updated_at.strftime("%d-%m-%Y") %></small>
    </div>
  </div>
<% end %>

app/views/groups/edit.html.erb
<%= render "form", group: @group %>

app/views/groups/index.html.erb
<div class="index_items">
  <%= render @groups %>
</div>

<div class="actions">
  <%= render "shared/notice" %>
  <%= button_to "New Category", new_group_path, method: :get, class: "green" %>
</div>

app/views/groups/new.html.erb
<%= render "form", group: @group %>

app/views/groups/show.html.erb
<div class="index_items">
  <div class="group box">
    <h2>
      <%= image_tag @group.icon || 'icon', style: 'height:64px;width:64px', class: 'grp-icon' %>
      <span><%= @group.name %></span>
      <small>$<%= @group.price %></small>
    </h2>
  </div>
  <%= render @transactions %>
</div>

<div class="actions">
  <%= render "shared/notice" %>
  <%= button_to "New Transaction", new_entity_path(@group.id), method: :get, class: 'green' %>
</div>

app/views/layouts/_header.html.erb
<header>
  <h3><%= link_to '<', :back %></h3>
  <%= link_to @header[:title].upcase, groups_url %>
  <% if @header[:url] %>
    <h3><%= link_to (@header[:urltxt] || '✎'), @header[:url] %></h3>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EconoMe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,700;1,300&display=swap" rel="stylesheet"> 
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if @header %>
      <%= render 'layouts/header' %>
    <% end %>
    <section>
      <%= yield %>
    </section>
  </body>
</html>

app/views/shared/_notice.html.erb
<div class="notice"><%= notice %></div>
<div class="alert"><%= alert %></div>

app/views/splash/home.html.erb
<div class="header">
  <h1 class="headline text ecno">Econo<span class="headline text me">Me</span></h1>
  <%# <h1 class="headline swash">rix..z</h1> %>
  <%# <h1 class="headline swash">rigxm</h1> %>
  <h1 class="headline swash">i</h1>
</div>

<div class="main_buttons">
  <%= button_to t('login'), new_user_session_path, method: :get, class: 'main_btn active' %>
  <%= button_to t('sign_up'), new_user_registration_path, method: :get, class: 'main_btn' %>
</div>